[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "bridge_fungible_token.sw"
license = "Apache-2.0"
name = "bridge_fungible_token"

[dependencies]
bridge_abi = { path = "../bridge-abi" }
frc20_abi = { path = "../frc20_abi"}
contract_message_receiver = { path = "../bridge-message-predicates/contract-message-receiver" }
