[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
entry = "main.sw"
license = "Apache-2.0"
name = "bridge_fungible_token"

[dependencies]
contract_message_receiver = { path = "../bridge-message-predicates/contract-message-receiver" }
bridge_fungible_token_abi = { path = "../fungible-token-abi" }
