/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface FuelMessageInboxInterface extends ethers.utils.Interface {
  functions: {
    "ETH_DECIMALS()": FunctionFragment;
    "FUEL_BASE_ASSET_DECIMALS()": FunctionFragment;
    "MESSAGE_OUTBOX()": FunctionFragment;
    "commitMessageRoot(bytes32)": FunctionFragment;
    "computeMessageId(bytes32,bytes32,bytes32,uint64,bytes)": FunctionFragment;
    "getFuelBaseAssetDecimals()": FunctionFragment;
    "getMessageSender()": FunctionFragment;
    "owner()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "relayMessage(bytes32,bytes32,bytes32,uint64,bytes,tuple)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "s_messageRoots(bytes32)": FunctionFragment;
    "s_successfulMessages(bytes32)": FunctionFragment;
    "serializeMessage(bytes32,bytes32,bytes32,uint64,bytes)": FunctionFragment;
    "setMessageRootCommitter(address)": FunctionFragment;
    "setMessageRootTimelock(uint64)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ETH_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FUEL_BASE_ASSET_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MESSAGE_OUTBOX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitMessageRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeMessageId",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFuelBaseAssetDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMessageSender",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "relayMessage",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      {
        root: BytesLike;
        key: BigNumberish;
        numLeaves: BigNumberish;
        proof: BytesLike[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_messageRoots",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "s_successfulMessages",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeMessage",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMessageRootCommitter",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMessageRootTimelock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "ETH_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FUEL_BASE_ASSET_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MESSAGE_OUTBOX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitMessageRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeMessageId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFuelBaseAssetDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMessageSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "relayMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_messageRoots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_successfulMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMessageRootCommitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMessageRootTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "RelayedMessage(bytes32)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayedMessage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export class FuelMessageInbox extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: FuelMessageInboxInterface;

  functions: {
    ETH_DECIMALS(overrides?: CallOverrides): Promise<[BigNumber]>;

    "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    FUEL_BASE_ASSET_DECIMALS(overrides?: CallOverrides): Promise<[BigNumber]>;

    "FUEL_BASE_ASSET_DECIMALS()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    MESSAGE_OUTBOX(overrides?: CallOverrides): Promise<[string]>;

    "MESSAGE_OUTBOX()"(overrides?: CallOverrides): Promise<[string]>;

    commitMessageRoot(
      messageRoot: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "commitMessageRoot(bytes32)"(
      messageRoot: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    computeMessageId(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "computeMessageId(bytes32,bytes32,bytes32,uint64,bytes)"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getFuelBaseAssetDecimals(overrides?: CallOverrides): Promise<[number]>;

    "getFuelBaseAssetDecimals()"(overrides?: CallOverrides): Promise<[number]>;

    getMessageSender(overrides?: CallOverrides): Promise<[string]>;

    "getMessageSender()"(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    "paused()"(overrides?: CallOverrides): Promise<[boolean]>;

    relayMessage(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      merkleProof: {
        root: BytesLike;
        key: BigNumberish;
        numLeaves: BigNumberish;
        proof: BytesLike[];
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "relayMessage(bytes32,bytes32,bytes32,uint64,bytes,(bytes32,uint256,uint256,bytes32[]))"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      merkleProof: {
        root: BytesLike;
        key: BigNumberish;
        numLeaves: BigNumberish;
        proof: BytesLike[];
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    s_messageRoots(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "s_messageRoots(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    s_successfulMessages(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "s_successfulMessages(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    serializeMessage(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "serializeMessage(bytes32,bytes32,bytes32,uint64,bytes)"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setMessageRootCommitter(
      messageRootCommitter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setMessageRootCommitter(address)"(
      messageRootCommitter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMessageRootTimelock(
      messageRootTimelock: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setMessageRootTimelock(uint64)"(
      messageRootTimelock: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ETH_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

  "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

  FUEL_BASE_ASSET_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

  "FUEL_BASE_ASSET_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

  MESSAGE_OUTBOX(overrides?: CallOverrides): Promise<string>;

  "MESSAGE_OUTBOX()"(overrides?: CallOverrides): Promise<string>;

  commitMessageRoot(
    messageRoot: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "commitMessageRoot(bytes32)"(
    messageRoot: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  computeMessageId(
    sender: BytesLike,
    recipient: BytesLike,
    nonce: BytesLike,
    amount: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "computeMessageId(bytes32,bytes32,bytes32,uint64,bytes)"(
    sender: BytesLike,
    recipient: BytesLike,
    nonce: BytesLike,
    amount: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getFuelBaseAssetDecimals(overrides?: CallOverrides): Promise<number>;

  "getFuelBaseAssetDecimals()"(overrides?: CallOverrides): Promise<number>;

  getMessageSender(overrides?: CallOverrides): Promise<string>;

  "getMessageSender()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "pause()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  relayMessage(
    sender: BytesLike,
    recipient: BytesLike,
    nonce: BytesLike,
    amount: BigNumberish,
    data: BytesLike,
    merkleProof: {
      root: BytesLike;
      key: BigNumberish;
      numLeaves: BigNumberish;
      proof: BytesLike[];
    },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "relayMessage(bytes32,bytes32,bytes32,uint64,bytes,(bytes32,uint256,uint256,bytes32[]))"(
    sender: BytesLike,
    recipient: BytesLike,
    nonce: BytesLike,
    amount: BigNumberish,
    data: BytesLike,
    merkleProof: {
      root: BytesLike;
      key: BigNumberish;
      numLeaves: BigNumberish;
      proof: BytesLike[];
    },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "renounceOwnership()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  s_messageRoots(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "s_messageRoots(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  s_successfulMessages(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "s_successfulMessages(bytes32)"(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  serializeMessage(
    sender: BytesLike,
    recipient: BytesLike,
    nonce: BytesLike,
    amount: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "serializeMessage(bytes32,bytes32,bytes32,uint64,bytes)"(
    sender: BytesLike,
    recipient: BytesLike,
    nonce: BytesLike,
    amount: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  setMessageRootCommitter(
    messageRootCommitter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setMessageRootCommitter(address)"(
    messageRootCommitter: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMessageRootTimelock(
    messageRootTimelock: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setMessageRootTimelock(uint64)"(
    messageRootTimelock: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "unpause()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ETH_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

    FUEL_BASE_ASSET_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    "FUEL_BASE_ASSET_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

    MESSAGE_OUTBOX(overrides?: CallOverrides): Promise<string>;

    "MESSAGE_OUTBOX()"(overrides?: CallOverrides): Promise<string>;

    commitMessageRoot(
      messageRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "commitMessageRoot(bytes32)"(
      messageRoot: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    computeMessageId(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "computeMessageId(bytes32,bytes32,bytes32,uint64,bytes)"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getFuelBaseAssetDecimals(overrides?: CallOverrides): Promise<number>;

    "getFuelBaseAssetDecimals()"(overrides?: CallOverrides): Promise<number>;

    getMessageSender(overrides?: CallOverrides): Promise<string>;

    "getMessageSender()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    "pause()"(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    relayMessage(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      merkleProof: {
        root: BytesLike;
        key: BigNumberish;
        numLeaves: BigNumberish;
        proof: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "relayMessage(bytes32,bytes32,bytes32,uint64,bytes,(bytes32,uint256,uint256,bytes32[]))"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      merkleProof: {
        root: BytesLike;
        key: BigNumberish;
        numLeaves: BigNumberish;
        proof: BytesLike[];
      },
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    s_messageRoots(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "s_messageRoots(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_successfulMessages(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "s_successfulMessages(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    serializeMessage(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "serializeMessage(bytes32,bytes32,bytes32,uint64,bytes)"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    setMessageRootCommitter(
      messageRootCommitter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMessageRootCommitter(address)"(
      messageRootCommitter: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMessageRootTimelock(
      messageRootTimelock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setMessageRootTimelock(uint64)"(
      messageRootTimelock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;

    "unpause()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    Paused(account: null): TypedEventFilter<[string], { account: string }>;

    RelayedMessage(
      messageId: BytesLike | null
    ): TypedEventFilter<[string], { messageId: string }>;

    Unpaused(account: null): TypedEventFilter<[string], { account: string }>;
  };

  estimateGas: {
    ETH_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

    FUEL_BASE_ASSET_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    "FUEL_BASE_ASSET_DECIMALS()"(overrides?: CallOverrides): Promise<BigNumber>;

    MESSAGE_OUTBOX(overrides?: CallOverrides): Promise<BigNumber>;

    "MESSAGE_OUTBOX()"(overrides?: CallOverrides): Promise<BigNumber>;

    commitMessageRoot(
      messageRoot: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "commitMessageRoot(bytes32)"(
      messageRoot: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    computeMessageId(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "computeMessageId(bytes32,bytes32,bytes32,uint64,bytes)"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFuelBaseAssetDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    "getFuelBaseAssetDecimals()"(overrides?: CallOverrides): Promise<BigNumber>;

    getMessageSender(overrides?: CallOverrides): Promise<BigNumber>;

    "getMessageSender()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    relayMessage(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      merkleProof: {
        root: BytesLike;
        key: BigNumberish;
        numLeaves: BigNumberish;
        proof: BytesLike[];
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "relayMessage(bytes32,bytes32,bytes32,uint64,bytes,(bytes32,uint256,uint256,bytes32[]))"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      merkleProof: {
        root: BytesLike;
        key: BigNumberish;
        numLeaves: BigNumberish;
        proof: BytesLike[];
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    s_messageRoots(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "s_messageRoots(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_successfulMessages(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "s_successfulMessages(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    serializeMessage(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "serializeMessage(bytes32,bytes32,bytes32,uint64,bytes)"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setMessageRootCommitter(
      messageRootCommitter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setMessageRootCommitter(address)"(
      messageRootCommitter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMessageRootTimelock(
      messageRootTimelock: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setMessageRootTimelock(uint64)"(
      messageRootTimelock: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ETH_DECIMALS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ETH_DECIMALS()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    FUEL_BASE_ASSET_DECIMALS(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "FUEL_BASE_ASSET_DECIMALS()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MESSAGE_OUTBOX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MESSAGE_OUTBOX()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    commitMessageRoot(
      messageRoot: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "commitMessageRoot(bytes32)"(
      messageRoot: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    computeMessageId(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "computeMessageId(bytes32,bytes32,bytes32,uint64,bytes)"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFuelBaseAssetDecimals(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFuelBaseAssetDecimals()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMessageSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getMessageSender()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "pause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    relayMessage(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      merkleProof: {
        root: BytesLike;
        key: BigNumberish;
        numLeaves: BigNumberish;
        proof: BytesLike[];
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "relayMessage(bytes32,bytes32,bytes32,uint64,bytes,(bytes32,uint256,uint256,bytes32[]))"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      merkleProof: {
        root: BytesLike;
        key: BigNumberish;
        numLeaves: BigNumberish;
        proof: BytesLike[];
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    s_messageRoots(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "s_messageRoots(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_successfulMessages(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "s_successfulMessages(bytes32)"(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    serializeMessage(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "serializeMessage(bytes32,bytes32,bytes32,uint64,bytes)"(
      sender: BytesLike,
      recipient: BytesLike,
      nonce: BytesLike,
      amount: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setMessageRootCommitter(
      messageRootCommitter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setMessageRootCommitter(address)"(
      messageRootCommitter: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMessageRootTimelock(
      messageRootTimelock: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setMessageRootTimelock(uint64)"(
      messageRootTimelock: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "unpause()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
