name: CI

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  RUST_VERSION: 1.70.0

jobs:
  lint-toml-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Install Cargo.toml linter
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-toml-lint
          version: '0.1.1'

      - name: Run Cargo.toml linter
        run: git ls-files | grep Cargo.toml$ | xargs --verbose -n 1 cargo-toml-lint

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: 
          [
            'bridge-fungible-token',
            'fungible-bridge-abi',
            'FRC20-abi',
            'test-deposit-recipient-contract'
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt

      - name: Init cache
        uses: Swatinem/rust-cache@v2

      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.6.0
        with:
          toolchain: latest
          date: 2023-07-05

      - name: Sway Formatting
        run: forc fmt --path ${{ matrix.project }} --check

      - name: Rust Formatting
        run: cd ${{ matrix.project }} && cargo fmt --verbose --check

      - name: Build Sway
        run: forc build --path ${{ matrix.project }}

      - name: Rust Tests
        if: ${{ matrix.project }} == "bridge-fungible-token"
        run: cd ${{ matrix.project }} && cargo test
